### ISSUE TITLE
[Feat] 근처 식당 조회 API 추가

### ISSUE THREAD

**Issue by wnsvy607** [Cheffi-Git/Cheffi-Server#192]
# 근처 식당 조회 API 추가

## Tasks
- [x] 근처 식당 조회 API 추가
  - [x] 컬럼 데피니션 변경(not null, geometry 타입)
  - [x] 공간 인덱스 적용
